#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely and handle SIGTERM by printing "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
